### ISSUE TITLE
Missleading error when wrong password

### ISSUE THREAD

**Issue by pnowojski** [kokosing/git-gifi#12]
Enter your Github password (will not be stored anywhere): 
Traceback (most recent call last):
  File "/home/piotr/py27-hfab/bin/gifi", line 11, in <module>
    sys.exit(main())
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/main.py", line 68, in main
    _main(args)
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/main.py", line 75, in _main
    result = command(*args)
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/command.py", line 35, in __call__
    return self.commands.get(commandName)(_commandArgs)
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/command.py", line 35, in **call**
    return self.commands.get(commandName)(_commandArgs)
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/command.py", line 9, in **call**
    return self.callable(_args, *_kwargs)
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/git_hub.py", line 20, in _authorize
    _create_authorization(config, config_level, gh)
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/git_hub.py", line 28, in _create_authorization
    _handle_github_exception(e, 'create an authorization')
  File "/home/piotr/py27-hfab/local/lib/python2.7/site-packages/gifi/git_hub.py", line 33, in _handle_github_exception
    error = ', '.join(map(_map_github_error, e.data['errors']))
KeyError: 'errors

**Comment by kokosing** [comment]
Fixed in version 0.6.
