### ISSUE TITLE
Feature-publish error when pushing a feature branch to a remote to which user does not have access.

### ISSUE THREAD

**Issue by kokosing** [kokosing/git-gifi#13]
```

[hadapt-ThinkPad-X220:~/Desktop/Hadapt/presto-master] (feature_concat) ⌘ git feature-publish 
Username for 'https://github.com': sopel39
Password for 'https://sopel39@github.com': 
Traceback (most recent call last):
File "/usr/local/bin/gifi", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/gifi/main.py", line 68, in main
_main(args)
File "/usr/local/lib/python2.7/dist-packages/gifi/main.py", line 75, in _main
result = command(*args)
File "/usr/local/lib/python2.7/dist-packages/gifi/command.py", line 35, in _call_
return self.commands.get(commandName)(*commandArgs)
File "/usr/local/lib/python2.7/dist-packages/gifi/command.py", line 35, in _call_
return self.commands.get(commandName)(*commandArgs)
File "/usr/local/lib/python2.7/dist-packages/gifi/command.py", line 9, in _call_
return self.callable(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/gifi/feature.py", line 41, in _publish
repo.git.push('-f', '-u', 'origin', 'HEAD:%s' % current_branch)
File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 440, in <lambda>
return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 834, in _call_process
return self.execute(make_call(), **_kwargs)
File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 627, in execute
raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git push -f -u origin HEAD:feature_concat' returned with exit code 128
stderr: 'remote: Permission to facebook/presto.git denied to sopel39.
fatal: unable to access 'https://github.com/facebook/presto.git/': The requested URL returned error: 403'
```

**Comment by kokosing** [comment]
Fixed in 0.8
