### ISSUE TITLE
Cannot configure slack

### ISSUE THREAD

**Issue by losipiuk** [kokosing/git-gifi#6]
I get following error when trying to configure slack:

```
$ gifi slack configure
Traceback (most recent call last):
  File "/home/losipiuk/python_work/bin/gifi", line 11, in <module>
    sys.exit(main())
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/main.py", line 65, in main
    _main(args)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/main.py", line 72, in _main
    result = command(*args)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/command.py", line 35, in __call__
    return self.commands.get(commandName)(*commandArgs)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/command.py", line 35, in __call__
    return self.commands.get(commandName)(*commandArgs)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/command.py", line 9, in __call__
    return self.callable(*args, **kwargs)
TypeError: <lambda>() takes exactly 1 argument (0 given)
```

**Comment by losipiuk** [comment]
Come on man - you can do better ;)

**Comment by kokosing** [comment]
Try following temporary solution:
`gifi slack configure global`
