### ISSUE TITLE
github authenticate does not work

### ISSUE THREAD

**Issue by losipiuk** [kokosing/git-gifi#7]
I get following error

```
⌘ gifi github authenticate
Github login (not-set): losipiuk
Traceback (most recent call last):
  File "/home/losipiuk/python_work/bin/gifi", line 11, in <module>
    sys.exit(main())
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/main.py", line 65, in main
    _main(args)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/main.py", line 72, in _main
    result = command(*args)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/command.py", line 35, in __call__
    return self.commands.get(commandName)(*commandArgs)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/command.py", line 35, in __call__
    return self.commands.get(commandName)(*commandArgs)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/command.py", line 9, in __call__
    return self.callable(*args, **kwargs)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/git_hub.py", line 13, in _authenticate
    config.configure(['login'])
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/internal/configuration.py", line 66, in configure
    self.set(key, self._parse_value(new_value, type(current_value)), config_level)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/gifi/internal/configuration.py", line 40, in set
    config_writer = self.repo.config_writer(config_level)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/git/repo/base.py", line 417, in config_writer
    return GitConfigParser(self._get_config_path(config_level), read_only=False)
  File "/home/losipiuk/python_work/local/lib/python2.7/site-packages/git/repo/base.py", line 380, in _get_config_path
    raise ValueError("Invalid configuration level: %r" % config_level)
ValueError: Invalid configuration level: ['login']
```

**Comment by kokosing** [comment]
Fixed in 0.3 version.
